apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-cli
    app.kubernetes.io/part-of: ec-release-debugging
  name: ec-cli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ec-cli
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ec-cli
    spec:
      containers:
      - image: quay.io/jstuart/ec-cli@sha256:e5ea6e2d8766fe560f1f24e4e9250ba023f1f27a914e484c9edb82d6018b2372
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
