apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-cli
    app.kubernetes.io/part-of: ec-release-debugging
  name: ec-cli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ec-cli
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ec-cli
    spec:
      containers:
      - image: quay.io/jstuart/ec-cli@sha256:fb40bcec4af3eeb9f71f44b0ce3e463c4eaf51b3d5e88931d3ed49f973245fc2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
