apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ec-cli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jstuart/ec-cli@sha256:24266633f235052ba0113f0576bf5c4dcc190d94b91aa22c3555daeb6382fe70
        name: container-image
        resources: {}
status: {}
