apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ec-cli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jstuart/ec-cli@sha256:3989099cd47b8a50602e06d101a522f7e5a0c7ece4354a5b1a58913de3a478dd
        name: container-image
        resources: {}
status: {}
