apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-cli
    app.kubernetes.io/part-of: ec-release-debugging
  name: ec-cliean8
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ec-cli
    weight: 100
status: {}
